/**
 * App-to-Agent WebSocket Schemas
 * Zod schemas for app-to-agent communication
 */

// Re-export schemas from their original source files
export {
  // Browser service response schemas
  BrowserActionResponseDataSchema,
  NewPageResponseSchema,
  ScrollResponseSchema,
  TypeResponseSchema,
  ClickResponseSchema,
  EnterResponseSchema,
  SearchResponseSchema,
  GetUrlResponseSchema,
  GoToPageResponseSchema,
  ScreenshotResponseSchema,
  HtmlReceivedSchema,
  GetMarkdownResponseSchema,
  GetContentResponseSchema,
  GetSnapShotResponseSchema,
  GetBrowserInfoResponseSchema,
  ExtractTextResponseSchema,
  BrowserServiceResponseSchema,
  // Chat service response schemas
  ChatHistoryResponseSchema,
  WaitForReplyResponseSchema,
  ConfirmationResponseSchema,
  FeedbackResponseSchema,
  // Terminal service response schemas
  CommandOutputResponseSchema,
  CommandErrorResponseSchema,
  CommandFinishResponseSchema,
  TerminalInterruptResponseSchema,
  TerminalServiceResponseSchema,
  // Project service response schemas
  GetProjectSettingsResponseSchema,
  GetProjectPathResponseSchema,
  GetRepoMapResponseSchema,
  GetEditorFileStatusResponseSchema,
  ProjectServiceResponseSchema,
  // Task service response schemas
  TaskResponseSchema,
  AddTaskResponseSchema,
  GetTasksResponseSchema,
  UpdateTasksResponseSchema,
  DeleteTaskResponseSchema,
  AddSubTaskResponseSchema,
  UpdateSubTaskResponseSchema,
  GetTasksByAgentResponseSchema,
  TaskServiceResponseSchema,
  // LLM service response schemas
  LLMResponseSchema,
  LLMServiceResponseSchema,
  // State service response schemas
  GetAppStateResponseSchema,
  AddToAgentStateResponseSchema,
  GetAgentStateResponseSchema,
  GetProjectStateResponseSchema,
  UpdateProjectStateResponseSchema,
  StateServiceResponseSchema,
  // VectorDB service response schemas
  GetVectorResponseSchema,
  AddVectorItemResponseSchema,
  QueryVectorItemResponseSchema,
  QueryVectorItemsResponseSchema,
  VectorDBServiceResponseSchema,
  // Utils service response schemas
  EditFileAndApplyDiffResponseSchema,
  UtilsServiceResponseSchema,
  // Tokenizer service response schemas
  AddTokenResponseSchema,
  GetTokenResponseSchema,
  TokenizerServiceResponseSchema,
  // MCP service response schemas
  GetEnabledToolBoxesResponseSchema,
  GetLocalToolBoxesResponseSchema,
  GetAvailableToolBoxesResponseSchema,
  SearchAvailableToolBoxesResponseSchema,
  ListToolsFromToolBoxesResponseSchema,
  ConfigureToolBoxResponseSchema,
  GetToolsResponseSchema,
  ExecuteToolResponseSchema,
  MCPServiceResponseSchema,
  // Debug service response schemas
  DebugAddLogResponseSchema,
  OpenDebugBrowserResponseSchema,
  GetDebugLogsResponseSchema,
  DebugServiceResponseSchema,
  // DB Memory service response schemas
  MemorySetResponseSchema,
  MemoryGetResponseSchema,
  DBMemoryServiceResponseSchema,
  // Code Utils service response schemas
  GetJsTreeResponseSchema,
  GetAllFilesAsMarkdownResponseSchema,
  MatchProblemResponseSchema,
  GetMatcherListTreeResponseSchema,
  GetMatchDetailResponseSchema,
  CodeUtilsServiceResponseSchema,
  // Crawler service response schemas
  CrawlResponseSchema,
  CrawlerServiceResponseSchema,
  // FS service response schemas
  CreateFileSuccessResponseSchema,
  CreateFileErrorResponseSchema,
  CreateFolderSuccessResponseSchema,
  CreateFolderErrorResponseSchema,
  ReadFileSuccessResponseSchema,
  ReadFileSuccessResultResponseSchema,
  UpdateFileSuccessResponseSchema,
  UpdateFileErrorResponseSchema,
  DeleteFileSuccessResponseSchema,
  DeleteFileErrorResponseSchema,
  DeleteFolderSuccessResponseSchema,
  DeleteFolderErrorResponseSchema,
  FileListSuccessResponseSchema,
  FileListErrorResponseSchema,
  SearchFilesSuccessResponseSchema,
  SearchFilesErrorResponseSchema,
  WriteToFileSuccessResponseSchema,
  WriteToFileErrorResponseSchema,
  GrepSearchSuccessResponseSchema,
  GrepSearchErrorResponseSchema,
  ListCodeDefinitionNamesSuccessResponseSchema,
  ListCodeDefinitionNamesErrorResponseSchema,
  FileSearchSuccessResponseSchema,
  FileSearchErrorResponseSchema,
  EditFileAndApplyDiffSuccessResponseSchema,
  EditFileAndApplyDiffErrorResponseSchema,
  FsServiceResponseSchema,
  // Git service response schemas
  GitInitResponseSchema,
  GitPullResponseSchema,
  GitPushResponseSchema,
  GitStatusResponseSchema,
  GitAddResponseSchema,
  GitCommitResponseSchema,
  GitCheckoutResponseSchema,
  GitBranchResponseSchema,
  GitLogsResponseSchema,
  GitDiffResponseSchema,
  GitServiceResponseSchema,
  // Agent service response schemas
  FindAgentByTaskResponseSchema,
  ListAgentsResponseSchema,
  AgentsDetailResponseSchema,
  TaskCompletionResponseSchema,
  AgentServiceErrorResponseSchema,
  AgentServiceResponseSchema,
  GetSummarizeAllResponseSchema,
  GetSummarizeResponseSchema,

} from './wstypes/app-to-agent-ws/indexResponses'; 